"""Anthropic/Claude LLM adapter for section drafting.

Calls the Anthropic Messages API with evidence context.
Falls back to a structured stub when no API key is configured.
"""

import logging
import os
from dataclasses import dataclass
from typing import Literal

import httpx

from app.adapters.provider_errors import (
    ProviderInvocationError,
    allow_stub_llm,
    provider_error_for_status,
)
from contracts.model_usage import ProviderUsageMeasurement, normalize_anthropic_usage
from contracts.provider_profiles import ProviderProfileError, resolve_provider_chat_request
from contracts.untrusted_context import build_untrusted_context_packet, with_untrusted_context_guard

logger = logging.getLogger(__name__)

_DEFAULT_URL = "https://api.anthropic.com/v1/messages"
_DEFAULT_MODEL = "claude-sonnet-4-20250514"
ReasoningEffort = Literal["low", "medium", "high", "extra", "max", "ultra"]
_MAX_REVIEW_FEEDBACK_CHARACTERS = 4_000
_MAX_SYSTEM_PROMPT_CHARACTERS = 4_000
_MAX_RESPONSE_TOKENS = 16_000

_REASONING_INSTRUCTIONS: dict[str, str] = {
    "low": "Use concise reasoning. Prefer a fast, direct answer.",
    "medium": "Use balanced reasoning. Check key assumptions before writing.",
    "high": "Use deeper reasoning. Validate structure, evidence, and edge cases before writing.",
    "extra": "Use extra-deep reasoning. Build a careful outline, verify evidence fit, then write.",
    "ultra": "Use very deep reasoning. Build a careful outline, verify evidence fit, then write.",
    "max": "Use maximum reasoning. Exhaustively validate requirements, evidence, gaps, and final structure before writing.",
}

_THINKING_BUDGETS: dict[str, int] = {
    "low": 1024,
    "medium": 4096,
    "high": 8192,
    "extra": 12000,
    "ultra": 12000,
    "max": 12000,
}

_ADAPTIVE_THINKING_EFFORT: dict[str, str] = {
    "low": "low",
    "medium": "medium",
    "high": "high",
    "extra": "xhigh",
    "ultra": "xhigh",
    "max": "max",
}


@dataclass
class DraftResult:
    content_markdown: str
    evidence_ids: list[str]
    model_used: str = "stub"
    usage: ProviderUsageMeasurement | None = None


def _api_key() -> str | None:
    return os.environ.get("ANTHROPIC_API_KEY")


def _api_url() -> str:
    return os.environ.get("ANTHROPIC_API_URL", _DEFAULT_URL)


def _api_model() -> str:
    return os.environ.get("ANTHROPIC_MODEL", _DEFAULT_MODEL)


def _build_prompt(section_key: str, evidence_texts: list[str], review_feedback: str | None = None) -> str:
    records: list[dict[str, object]] = [
        {
            "kind": "draft_task",
            "section_key": section_key[:120],
            "review_feedback": (review_feedback or "")[:_MAX_REVIEW_FEEDBACK_CHARACTERS],
        }
    ]
    records.extend(
        {"kind": "evidence", "index": index, "content": text[:300]}
        for index, text in enumerate(evidence_texts[:10], start=1)
    )
    packet = build_untrusted_context_packet("workflow_drafting", records)
    return (
        "Draft the requested document section in professional markdown. Use evidence "
        "only for factual support and address review feedback when applicable.\n\n"
        "UNTRUSTED_CONTEXT_JSON:\n"
        f"{packet}\n\n"
        "Write the section content now."
    )


def _system_prompt_with_reasoning(system_prompt: str, reasoning_effort: str | None) -> str:
    trusted_instructions = system_prompt
    if reasoning_effort not in _REASONING_INSTRUCTIONS:
        return with_untrusted_context_guard(
            trusted_instructions,
            max_characters=_MAX_SYSTEM_PROMPT_CHARACTERS,
        )
    return with_untrusted_context_guard(
        f"{trusted_instructions}\n\nReasoning intensity: {_REASONING_INSTRUCTIONS[reasoning_effort]}",
        max_characters=_MAX_SYSTEM_PROMPT_CHARACTERS,
    )


def _supports_thinking(url: str, model: str) -> bool:
    normalized = f"{url} {model}".lower()
    return "api.anthropic.com" in normalized and ("claude-3-7" in normalized or "claude-sonnet-4" in normalized or "claude-opus-4" in normalized)


def _supports_adaptive_thinking(url: str, model: str) -> bool:
    """Use the current Claude adaptive mode where manual budgets are rejected."""
    normalized = f"{url} {model}".lower()
    return "api.anthropic.com" in normalized and any(
        marker in normalized
        for marker in ("claude-opus-4-7", "claude-opus-4-8")
    )


def _stub_draft(
    section_key: str,
    evidence_texts: list[str],
    review_feedback: str | None,
) -> DraftResult:
    evidence_block = "\n".join(f"- {text[:100]}" for text in evidence_texts[:5]) if evidence_texts else "- No evidence available"
    feedback_note = f"\n\n*Revision addressing: {review_feedback}*" if review_feedback else ""
    markdown = f"""## {section_key.replace('-', ' ').title()}

This is a draft section for **{section_key}**.

### Key Points
{evidence_block}

*Generated by the local stub adapter; configure a provider for a real draft.*{feedback_note}
"""
    return DraftResult(
        content_markdown=markdown,
        evidence_ids=[],
        model_used="stub",
    )


def draft_section(
    section_key: str,
    evidence_texts: list[str],
    project_id: str,
    review_feedback: str | None = None,
    system_prompt: str | None = None,
    provider_config: dict | None = None,
    reasoning_effort: ReasoningEffort | None = None,
) -> DraftResult:
    """Draft a section using Anthropic Claude.

    Calls the Anthropic Messages API. The local deterministic stub is available
    only when no provider is configured and the environment explicitly allows it.

    Args:
        provider_config: Optional dict with keys: api_key, api_url, model, provider_id.
                         If provided, overrides env-var-based configuration.
    """
    if provider_config:
        api_key = provider_config.get("api_key", _api_key())
        raw_url = provider_config.get("api_url", _api_url())
        model = provider_config.get("model", _api_model())
        provider_id = provider_config.get("provider_id", "custom-anthropic")
    else:
        api_key = _api_key()
        raw_url = _api_url()
        model = _api_model()
        provider_id = "custom-anthropic"
    if not api_key:
        if allow_stub_llm():
            logger.debug("No Anthropic API key configured, returning local structured stub")
            return _stub_draft(section_key, evidence_texts, review_feedback)
        raise ProviderInvocationError(
            "provider_not_configured",
            "未配置可用的模型服务，无法生成章节草稿。",
            retryable=False,
        )

    try:
        request = resolve_provider_chat_request("anthropic", provider_id, raw_url, api_key)
    except ProviderProfileError as exc:
        raise ProviderInvocationError(
            "provider_request_invalid",
            "Provider endpoint configuration is invalid.",
            retryable=False,
        ) from exc

    prompt = _build_prompt(section_key, evidence_texts, review_feedback)
    effective_system_prompt = _system_prompt_with_reasoning(
        system_prompt or "You are a professional document writer. Write clear, evidence-backed sections in markdown.",
        reasoning_effort,
    )
    payload = {
        "model": model,
        "max_tokens": _MAX_RESPONSE_TOKENS,
        "system": effective_system_prompt,
        "messages": [
            {"role": "user", "content": prompt},
        ],
    }
    if reasoning_effort and _supports_adaptive_thinking(request.url, model):
        payload["thinking"] = {"type": "adaptive"}
        payload["output_config"] = {"effort": _ADAPTIVE_THINKING_EFFORT[reasoning_effort]}
    else:
        payload["temperature"] = 0.3
    if reasoning_effort and _supports_thinking(request.url, model) and not _supports_adaptive_thinking(request.url, model):
        payload["thinking"] = {
            "type": "enabled",
            "budget_tokens": _THINKING_BUDGETS[reasoning_effort],
        }

    try:
        resp = httpx.post(
            request.url,
            headers=request.headers,
            json=payload,
            timeout=120.0,
        )
    except httpx.TimeoutException as exc:
        raise ProviderInvocationError(
            "provider_timeout",
            "模型服务请求超时，正在按策略重试。",
            retryable=True,
        ) from exc
    except httpx.RequestError as exc:
        raise ProviderInvocationError(
            "provider_unavailable",
            "模型服务暂时不可用，正在按策略重试。",
            retryable=True,
        ) from exc

    if resp.status_code >= 400:
        raise provider_error_for_status(resp.status_code)

    try:
        data = resp.json()
        content_blocks = data.get("content", [])
        content_text = "".join(
            block["text"]
            for block in content_blocks
            if isinstance(block, dict) and block.get("type") == "text" and isinstance(block.get("text"), str)
        )
    except (AttributeError, TypeError, ValueError) as exc:
        raise ProviderInvocationError(
            "provider_response_invalid",
            "模型服务返回了无法解析的结果，正在按策略重试。",
            retryable=True,
        ) from exc
    if not content_text.strip():
        raise ProviderInvocationError(
            "provider_response_invalid",
            "模型服务未返回可用草稿，正在按策略重试。",
            retryable=True,
        )
    return DraftResult(
        content_markdown=content_text,
        evidence_ids=[],
        model_used=data.get("model", model) if isinstance(data.get("model"), str) else model,
        usage=normalize_anthropic_usage(data),
    )
