"""Anthropic/Claude LLM adapter for section drafting.

Calls the Anthropic Messages API with evidence context.
Falls back to a structured stub when no API key is configured.
"""

import logging
import os
from dataclasses import dataclass

import httpx

logger = logging.getLogger(__name__)

_DEFAULT_URL = "https://api.anthropic.com/v1/messages"
_DEFAULT_MODEL = "claude-sonnet-4-20250514"


@dataclass
class DraftResult:
    content_markdown: str
    evidence_ids: list[str]
    model_used: str = "stub"


def _api_key() -> str | None:
    return os.environ.get("ANTHROPIC_API_KEY")


def _api_url() -> str:
    return os.environ.get("ANTHROPIC_API_URL", _DEFAULT_URL)


def _api_model() -> str:
    return os.environ.get("ANTHROPIC_MODEL", _DEFAULT_MODEL)


def _build_prompt(section_key: str, evidence_texts: list[str], review_feedback: str | None = None) -> str:
    evidence_block = "\n".join(f"- {t[:300]}" for t in evidence_texts[:10]) if evidence_texts else "- No evidence available"
    feedback_block = ""
    if review_feedback:
        feedback_block = f"""
### Review Feedback (address this in the revision):
{review_feedback}
"""
    return f"""You are drafting a section for a document.

Section: {section_key.replace('-', ' ').title()}

Use the following evidence to write a professional, well-structured section in markdown.
Cite specific evidence where appropriate.
{feedback_block}
Evidence:
{evidence_block}

Write the section content now:"""


def draft_section(section_key: str, evidence_texts: list[str], project_id: str, review_feedback: str | None = None, system_prompt: str | None = None, provider_config: dict | None = None) -> DraftResult:
    """Draft a section using Anthropic Claude.

    Calls the Anthropic Messages API. Falls back to a structured stub if unavailable.

    Args:
        provider_config: Optional dict with keys: api_key, api_url, model.
                         If provided, overrides env-var-based configuration.
    """
    if provider_config:
        api_key = provider_config.get("api_key", _api_key())
        url = provider_config.get("api_url", _api_url())
        model = provider_config.get("model", _api_model())
    else:
        api_key = _api_key()
        url = _api_url()
        model = _api_model()
    if not api_key:
        logger.debug("No Anthropic API key configured, returning structured stub")
        evidence_block = "\n".join(f"- {t[:100]}" for t in evidence_texts[:5]) if evidence_texts else "- No evidence available"
        feedback_note = f"\n\n*Revision addressing: {review_feedback}*" if review_feedback else ""
        markdown = f"""## {section_key.replace('-', ' ').title()}

This is a draft section for **{section_key}**.

### Key Points
{evidence_block}

*Generated by Anthropic stub adapter (configure ANTHROPIC_API_KEY for real output)*{feedback_note}
"""
        return DraftResult(
            content_markdown=markdown,
            evidence_ids=[],
            model_used="stub",
        )

    prompt = _build_prompt(section_key, evidence_texts, review_feedback)
    effective_system_prompt = system_prompt or "You are a professional document writer. Write clear, evidence-backed sections in markdown."

    try:
        resp = httpx.post(
            url,
            headers={
                "x-api-key": api_key,
                "anthropic-version": "2023-06-01",
                "content-type": "application/json",
            },
            json={
                "model": model,
                "max_tokens": 4000,
                "system": effective_system_prompt,
                "messages": [
                    {"role": "user", "content": prompt},
                ],
                "temperature": 0.3,
            },
            timeout=120.0,
        )
        resp.raise_for_status()
        data = resp.json()

        # Extract text from response content blocks
        content_text = ""
        for block in data.get("content", []):
            if block.get("type") == "text":
                content_text += block["text"]

        return DraftResult(
            content_markdown=content_text,
            evidence_ids=[],
            model_used=data.get("model", model),
        )
    except Exception as exc:
        logger.warning("Anthropic API call failed: %s, falling back to stub", exc)
        evidence_block = "\n".join(f"- {t[:100]}" for t in evidence_texts[:5]) if evidence_texts else "- No evidence available"
        markdown = f"""## {section_key.replace('-', ' ').title()}

*Anthropic API call failed — fallback draft*

### Key Points
{evidence_block}
"""
        return DraftResult(
            content_markdown=markdown,
            evidence_ids=[],
            model_used="fallback",
        )
