"""Anthropic/Claude LLM adapter for section drafting.

Calls the Anthropic Messages API with evidence context.
Falls back to a structured stub when no API key is configured.
"""

import logging
import os
from dataclasses import dataclass
from typing import Literal

import httpx

logger = logging.getLogger(__name__)

_DEFAULT_URL = "https://api.anthropic.com/v1/messages"
_DEFAULT_MODEL = "claude-sonnet-4-20250514"
ReasoningEffort = Literal["low", "medium", "high", "extra", "max", "ultra"]

_REASONING_INSTRUCTIONS: dict[str, str] = {
    "low": "Use concise reasoning. Prefer a fast, direct answer.",
    "medium": "Use balanced reasoning. Check key assumptions before writing.",
    "high": "Use deeper reasoning. Validate structure, evidence, and edge cases before writing.",
    "extra": "Use extra-deep reasoning. Build a careful outline, verify evidence fit, then write.",
    "ultra": "Use very deep reasoning. Build a careful outline, verify evidence fit, then write.",
    "max": "Use maximum reasoning. Exhaustively validate requirements, evidence, gaps, and final structure before writing.",
}

_THINKING_BUDGETS: dict[str, int] = {
    "low": 1024,
    "medium": 4096,
    "high": 8192,
    "extra": 16000,
    "ultra": 16000,
    "max": 32000,
}


@dataclass
class DraftResult:
    content_markdown: str
    evidence_ids: list[str]
    model_used: str = "stub"


def _api_key() -> str | None:
    return os.environ.get("ANTHROPIC_API_KEY")


def _api_url() -> str:
    return os.environ.get("ANTHROPIC_API_URL", _DEFAULT_URL)


def _api_model() -> str:
    return os.environ.get("ANTHROPIC_MODEL", _DEFAULT_MODEL)


def _build_prompt(section_key: str, evidence_texts: list[str], review_feedback: str | None = None) -> str:
    evidence_block = "\n".join(f"- {t[:300]}" for t in evidence_texts[:10]) if evidence_texts else "- No evidence available"
    feedback_block = ""
    if review_feedback:
        feedback_block = f"""
### Review Feedback (address this in the revision):
{review_feedback}
"""
    return f"""You are drafting a section for a document.

Section: {section_key.replace('-', ' ').title()}

Use the following evidence to write a professional, well-structured section in markdown.
Cite specific evidence where appropriate.
{feedback_block}
Evidence:
{evidence_block}

Write the section content now:"""


def _system_prompt_with_reasoning(system_prompt: str, reasoning_effort: str | None) -> str:
    if reasoning_effort not in _REASONING_INSTRUCTIONS:
        return system_prompt
    return f"{system_prompt}\n\nReasoning intensity: {_REASONING_INSTRUCTIONS[reasoning_effort]}"


def _supports_thinking(url: str, model: str) -> bool:
    normalized = f"{url} {model}".lower()
    return "api.anthropic.com" in normalized and ("claude-3-7" in normalized or "claude-sonnet-4" in normalized or "claude-opus-4" in normalized)


def draft_section(
    section_key: str,
    evidence_texts: list[str],
    project_id: str,
    review_feedback: str | None = None,
    system_prompt: str | None = None,
    provider_config: dict | None = None,
    reasoning_effort: ReasoningEffort | None = None,
) -> DraftResult:
    """Draft a section using Anthropic Claude.

    Calls the Anthropic Messages API. Falls back to a structured stub if unavailable.

    Args:
        provider_config: Optional dict with keys: api_key, api_url, model.
                         If provided, overrides env-var-based configuration.
    """
    if provider_config:
        api_key = provider_config.get("api_key", _api_key())
        url = provider_config.get("api_url", _api_url())
        model = provider_config.get("model", _api_model())
    else:
        api_key = _api_key()
        url = _api_url()
        model = _api_model()
    if not api_key:
        logger.debug("No Anthropic API key configured, returning structured stub")
        evidence_block = "\n".join(f"- {t[:100]}" for t in evidence_texts[:5]) if evidence_texts else "- No evidence available"
        feedback_note = f"\n\n*Revision addressing: {review_feedback}*" if review_feedback else ""
        markdown = f"""## {section_key.replace('-', ' ').title()}

This is a draft section for **{section_key}**.

### Key Points
{evidence_block}

*Generated by Anthropic stub adapter (configure ANTHROPIC_API_KEY for real output)*{feedback_note}
"""
        return DraftResult(
            content_markdown=markdown,
            evidence_ids=[],
            model_used="stub",
        )

    prompt = _build_prompt(section_key, evidence_texts, review_feedback)
    effective_system_prompt = _system_prompt_with_reasoning(
        system_prompt or "You are a professional document writer. Write clear, evidence-backed sections in markdown.",
        reasoning_effort,
    )
    payload = {
        "model": model,
        "max_tokens": 4000,
        "system": effective_system_prompt,
        "messages": [
            {"role": "user", "content": prompt},
        ],
        "temperature": 0.3,
    }
    if reasoning_effort and _supports_thinking(url, model):
        payload["thinking"] = {
            "type": "enabled",
            "budget_tokens": _THINKING_BUDGETS[reasoning_effort],
        }

    try:
        resp = httpx.post(
            url,
            headers={
                "x-api-key": api_key,
                "anthropic-version": "2023-06-01",
                "content-type": "application/json",
            },
            json=payload,
            timeout=120.0,
        )
        resp.raise_for_status()
        data = resp.json()

        # Extract text from response content blocks
        content_text = ""
        for block in data.get("content", []):
            if block.get("type") == "text":
                content_text += block["text"]

        return DraftResult(
            content_markdown=content_text,
            evidence_ids=[],
            model_used=data.get("model", model),
        )
    except Exception as exc:
        logger.warning("Anthropic API call failed: %s, falling back to stub", exc)
        evidence_block = "\n".join(f"- {t[:100]}" for t in evidence_texts[:5]) if evidence_texts else "- No evidence available"
        markdown = f"""## {section_key.replace('-', ' ').title()}

*Anthropic API call failed — fallback draft*

### Key Points
{evidence_block}
"""
        return DraftResult(
            content_markdown=markdown,
            evidence_ids=[],
            model_used="fallback",
        )
