"""LLM adapter for section drafting.

Calls an OpenAI-compatible chat completions API with evidence context.
Falls back to a structured stub when no API key is configured.
"""

import logging
from dataclasses import dataclass
from typing import Literal

import httpx

from app.adapters.provider_env import chat_api_key, chat_api_url, chat_model

logger = logging.getLogger(__name__)

_DEFAULT_URL = "https://api.openai.com/v1/chat/completions"
_DEFAULT_MODEL = "gpt-4o-mini"
ReasoningEffort = Literal["low", "medium", "high", "extra", "max", "ultra"]

_REASONING_INSTRUCTIONS: dict[str, str] = {
    "low": "Use concise reasoning. Prefer a fast, direct answer.",
    "medium": "Use balanced reasoning. Check key assumptions before writing.",
    "high": "Use deeper reasoning. Validate structure, evidence, and edge cases before writing.",
    "extra": "Use extra-deep reasoning. Build a careful outline, verify evidence fit, then write.",
    "ultra": "Use very deep reasoning. Build a careful outline, verify evidence fit, then write.",
    "max": "Use maximum reasoning. Exhaustively validate requirements, evidence, gaps, and final structure before writing.",
}

_OPENAI_REASONING_EFFORT: dict[str, str] = {
    "low": "low",
    "medium": "medium",
    "high": "high",
    "extra": "high",
    "ultra": "high",
    "max": "high",
}


@dataclass
class DraftResult:
    content_markdown: str
    evidence_ids: list[str]
    model_used: str = "stub"


def _api_key() -> str | None:
    return chat_api_key()


def _api_url() -> str:
    return chat_api_url(_DEFAULT_URL)


def _api_model() -> str:
    return chat_model(_DEFAULT_MODEL)


def _build_prompt(section_key: str, evidence_texts: list[str], review_feedback: str | None = None) -> str:
    evidence_block = "\n".join(f"- {t[:300]}" for t in evidence_texts[:10]) if evidence_texts else "- No evidence available"
    feedback_block = ""
    if review_feedback:
        feedback_block = f"""
### Review Feedback (address this in the revision):
{review_feedback}
"""
    return f"""You are drafting a section for a document.

Section: {section_key.replace('-', ' ').title()}

Use the following evidence to write a professional, well-structured section in markdown.
Cite specific evidence where appropriate.
{feedback_block}
Evidence:
{evidence_block}

Write the section content now:"""


def _supports_reasoning_effort(url: str, model: str) -> bool:
    normalized = f"{url} {model}".lower()
    return "api.openai.com" in normalized or model.lower().startswith(("o1", "o3", "o4", "gpt-5"))


def _system_prompt_with_reasoning(system_prompt: str, reasoning_effort: str | None) -> str:
    if reasoning_effort not in _REASONING_INSTRUCTIONS:
        return system_prompt
    return f"{system_prompt}\n\nReasoning intensity: {_REASONING_INSTRUCTIONS[reasoning_effort]}"


def draft_section(
    section_key: str,
    evidence_texts: list[str],
    project_id: str,
    review_feedback: str | None = None,
    system_prompt: str | None = None,
    provider_config: dict | None = None,
    reasoning_effort: ReasoningEffort | None = None,
) -> DraftResult:
    """Draft a section using evidence.

    Calls the configured LLM API. Falls back to a structured stub if unavailable.

    Args:
        provider_config: Optional dict with keys: api_key, api_url, model.
                         If provided, overrides env-var-based configuration.
    """
    if provider_config:
        api_key = provider_config.get("api_key", _api_key())
        url = provider_config.get("api_url", _api_url())
        model = provider_config.get("model", _api_model())
    else:
        api_key = _api_key()
        url = _api_url()
        model = _api_model()

    if not api_key:
        logger.debug("No LLM API key configured, returning structured stub")
        evidence_block = "\n".join(f"- {t[:100]}" for t in evidence_texts[:5]) if evidence_texts else "- No evidence available"
        feedback_note = f"\n\n*Revision addressing: {review_feedback}*" if review_feedback else ""
        markdown = f"""## {section_key.replace('-', ' ').title()}

This is a draft section for **{section_key}**.

### Key Points
{evidence_block}

*Generated by stub adapter (configure LLM_API_KEY for real output)*{feedback_note}
"""
        return DraftResult(
            content_markdown=markdown,
            evidence_ids=[],
            model_used="stub",
        )

    prompt = _build_prompt(section_key, evidence_texts, review_feedback)
    effective_system_prompt = _system_prompt_with_reasoning(
        system_prompt or "You are a professional document writer. Write clear, evidence-backed sections in markdown.",
        reasoning_effort,
    )
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": effective_system_prompt},
            {"role": "user", "content": prompt},
        ],
        "temperature": 0.3,
        "max_tokens": 2000,
    }
    if reasoning_effort and _supports_reasoning_effort(url, model):
        payload["reasoning_effort"] = _OPENAI_REASONING_EFFORT[reasoning_effort]

    try:
        resp = httpx.post(
            url,
            headers={"Authorization": f"Bearer {api_key}"},
            json=payload,
            timeout=60.0,
        )
        resp.raise_for_status()
        data = resp.json()
        content = data["choices"][0]["message"]["content"]
        return DraftResult(
            content_markdown=content,
            evidence_ids=[],
            model_used=model,
        )
    except Exception as exc:
        logger.warning("LLM API call failed: %s, falling back to stub", exc)
        evidence_block = "\n".join(f"- {t[:100]}" for t in evidence_texts[:5]) if evidence_texts else "- No evidence available"
        markdown = f"""## {section_key.replace('-', ' ').title()}

*LLM call failed — fallback draft*

### Key Points
{evidence_block}
"""
        return DraftResult(
            content_markdown=markdown,
            evidence_ids=[],
            model_used="fallback",
        )
