"""LLM adapter for section drafting.

Calls an OpenAI-compatible chat completions API with evidence context.
Falls back to a structured stub when no API key is configured.
"""

import logging
import os
from dataclasses import dataclass

import httpx

logger = logging.getLogger(__name__)

_DEFAULT_URL = "https://api.openai.com/v1/chat/completions"
_DEFAULT_MODEL = "gpt-4o-mini"


@dataclass
class DraftResult:
    content_markdown: str
    evidence_ids: list[str]
    model_used: str = "stub"


def _api_key() -> str | None:
    return os.environ.get("LLM_API_KEY") or os.environ.get("OPENAI_API_KEY")


def _api_url() -> str:
    return os.environ.get("LLM_API_URL", _DEFAULT_URL)


def _api_model() -> str:
    return os.environ.get("LLM_MODEL", _DEFAULT_MODEL)


def _build_prompt(section_key: str, evidence_texts: list[str], review_feedback: str | None = None) -> str:
    evidence_block = "\n".join(f"- {t[:300]}" for t in evidence_texts[:10]) if evidence_texts else "- No evidence available"
    feedback_block = ""
    if review_feedback:
        feedback_block = f"""
### Review Feedback (address this in the revision):
{review_feedback}
"""
    return f"""You are drafting a section for a document.

Section: {section_key.replace('-', ' ').title()}

Use the following evidence to write a professional, well-structured section in markdown.
Cite specific evidence where appropriate.
{feedback_block}
Evidence:
{evidence_block}

Write the section content now:"""


def draft_section(section_key: str, evidence_texts: list[str], project_id: str, review_feedback: str | None = None, system_prompt: str | None = None) -> DraftResult:
    """Draft a section using evidence.

    Calls the configured LLM API. Falls back to a structured stub if unavailable.
    """
    api_key = _api_key()
    if not api_key:
        logger.debug("No LLM API key configured, returning structured stub")
        evidence_block = "\n".join(f"- {t[:100]}" for t in evidence_texts[:5]) if evidence_texts else "- No evidence available"
        feedback_note = f"\n\n*Revision addressing: {review_feedback}*" if review_feedback else ""
        markdown = f"""## {section_key.replace('-', ' ').title()}

This is a draft section for **{section_key}**.

### Key Points
{evidence_block}

*Generated by stub adapter (configure LLM_API_KEY for real output)*{feedback_note}
"""
        return DraftResult(
            content_markdown=markdown,
            evidence_ids=[],
            model_used="stub",
        )

    url = _api_url()
    model = _api_model()
    prompt = _build_prompt(section_key, evidence_texts, review_feedback)
    effective_system_prompt = system_prompt or "You are a professional document writer. Write clear, evidence-backed sections in markdown."

    try:
        resp = httpx.post(
            url,
            headers={"Authorization": f"Bearer {api_key}"},
            json={
                "model": model,
                "messages": [
                    {"role": "system", "content": effective_system_prompt},
                    {"role": "user", "content": prompt},
                ],
                "temperature": 0.3,
                "max_tokens": 2000,
            },
            timeout=60.0,
        )
        resp.raise_for_status()
        data = resp.json()
        content = data["choices"][0]["message"]["content"]
        return DraftResult(
            content_markdown=content,
            evidence_ids=[],
            model_used=model,
        )
    except Exception as exc:
        logger.warning("LLM API call failed: %s, falling back to stub", exc)
        evidence_block = "\n".join(f"- {t[:100]}" for t in evidence_texts[:5]) if evidence_texts else "- No evidence available"
        markdown = f"""## {section_key.replace('-', ' ').title()}

*LLM call failed — fallback draft*

### Key Points
{evidence_block}
"""
        return DraftResult(
            content_markdown=markdown,
            evidence_ids=[],
            model_used="fallback",
        )
