"""add_user_disabled_column

Revision ID: 2e5dc6faa08e
Revises: 27bbad823c47
Create Date: 2026-05-03 19:22:38.401852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e5dc6faa08e'
down_revision: Union[str, Sequence[str], None] = '27bbad823c47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('user', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.execute('UPDATE "user" SET disabled = false WHERE disabled IS NULL')
    op.alter_column('user', 'disabled', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'disabled')
    # ### end Alembic commands ###
